server:
  port: 9443
  ssl:
    bundle: demo-authorizationserver
    client-auth: want

spring:
  ssl:
    bundle:
      jks:
        demo-authorizationserver:
          key:
            alias: demo-authorizationserver-sample
            password: password
          keystore:
            location: classpath:keystore.p12
            password: password
            type: PKCS12
          truststore:
            location: classpath:keystore.p12
            password: password
            type: PKCS12


logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO